import { rename, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { solutionPassesTests } from '../src/core/exercise'
import { COURSE_TARGET } from '../src/core/generation'
import { generatedToSeedCourse } from '../src/db/generated-to-seed'
import { BUILTIN_COURSES, type SeedCourse } from '../src/db/seed-content'
import { GENERATED_BUILTIN_COURSES } from '../src/db/seed-content.generated'
import { SEED_TOPICS } from '../src/db/seed-data'
import { openAiGenerator } from '../src/server/openai-generator'

// Topics whose learners actually write JavaScript — the only place a JS-runner
// exercise belongs. The prompt asks the model to omit exercises elsewhere, but it
// occasionally ignores that (e.g. a JS exercise in a Python course), so enforce it.
const JS_EXERCISE_SLUGS = new Set([
  'javascript',
  'typescript',
  'react',
  'nodejs',
  'nextjs',
])

// Prune a course's exercises: on non-JS topics drop them all; elsewhere keep only
// those whose model-written solution passes its own tests, so the committed
// built-ins always satisfy the seed-content ship gate. Mutates.
function pruneExercises(
  course: SeedCourse,
  allowExercises: boolean,
): { kept: number; dropped: number } {
  let kept = 0
  let dropped = 0
  for (const lesson of course.lessons) {
    for (const seg of lesson.segments) {
      if (!seg.exercise) continue
      const ok =
        allowExercises &&
        solutionPassesTests(seg.exercise.solution, seg.exercise.tests)
      if (ok) kept++
      else {
        delete seg.exercise
        dropped++
      }
    }
  }
  return { kept, dropped }
}

// Generate beginner "dive-in" starter courses for topics that lack a built-in
// one, then write them to src/db/seed-content.generated.ts for review + commit.
// Leverages the same generation pipeline the app uses at runtime.
//
//   npm run gen:builtins                 # fill every topic missing a built-in
//   npm run gen:builtins docker python   # (re)generate just these slugs
//   npm run gen:builtins all             # regenerate every non-hand-authored topic
//
// Needs OPENAI_API_KEY in .env (npm run loads it). OPENAI_MODEL overrides the
// model — defaults to gpt-4o here (higher quality than the per-user gpt-4o-mini,
// since this content ships to every user and is generated once).

const OUT_PATH = fileURLToPath(
  new URL('../src/db/seed-content.generated.ts', import.meta.url),
)

const HEADER = `/* eslint-disable */
// AUTO-GENERATED by scripts/gen-builtins.ts — do not edit by hand.
// Regenerate (needs OPENAI_API_KEY in .env): npm run gen:builtins [topic-slug ...]
// These are beginner "dive-in" starter courses so every topic card is instant
// and key-free; users wanting a harder/custom course pick a level and generate.
import type { SeedCourse } from './seed-content'

export const GENERATED_BUILTIN_COURSES: SeedCourse[] = `

async function main() {
  const apiKey = process.env.OPENAI_API_KEY
  if (!apiKey) {
    console.error('OPENAI_API_KEY is not set (add it to apps/web/.env).')
    process.exit(1)
  }
  const model = process.env.OPENAI_MODEL ?? 'gpt-4o'
  const generator = openAiGenerator(apiKey, { model })

  const rawArgs = process.argv.slice(2)
  const forceAll = rawArgs.some(
    (a) => a === 'all' || a === '--all' || a === '--force',
  )
  const slugArgs = rawArgs.filter((a) => !a.startsWith('--') && a !== 'all')
  const bySlug = new Map(SEED_TOPICS.map((t) => [t.slug, t]))

  // Hand-authored built-ins (e.g. git-github) live in seed-content.ts, not the
  // generated file — `all` regenerates everything except those.
  const generatedSlugs = new Set(GENERATED_BUILTIN_COURSES.map((c) => c.topicSlug))
  const handAuthored = new Set(
    BUILTIN_COURSES.filter((c) => !generatedSlugs.has(c.topicSlug)).map(
      (c) => c.topicSlug,
    ),
  )

  let targets: string[]
  if (forceAll) {
    targets = SEED_TOPICS.filter((t) => !handAuthored.has(t.slug)).map((t) => t.slug)
  } else if (slugArgs.length > 0) {
    const unknown = slugArgs.filter((s) => !bySlug.has(s))
    if (unknown.length > 0) {
      console.error(`Unknown topic slug(s): ${unknown.join(', ')}`)
      process.exit(1)
    }
    targets = slugArgs
  } else {
    const covered = new Set(BUILTIN_COURSES.map((c) => c.topicSlug))
    targets = SEED_TOPICS.filter((t) => !covered.has(t.slug)).map((t) => t.slug)
  }

  if (targets.length === 0) {
    console.log('Every topic already has a built-in course — nothing to generate.')
    console.log('Pass slugs (or `all`) to force regeneration, e.g. `npm run gen:builtins docker` / `npm run gen:builtins all`.')
    process.exit(0)
  }

  console.log(`Generating ${targets.length} course(s) with ${model}…`)
  const generated = new Map<string, SeedCourse>()
  const failed: string[] = []
  const MAX_ATTEMPTS = 4

  for (const slug of targets) {
    const topic = bySlug.get(slug)!
    process.stdout.write(`  • ${topic.name} (${slug})… `)
    try {
      // Re-roll up to MAX_ATTEMPTS for depth — the model sometimes under-delivers
      // on lesson count. Keep the deepest attempt; accept early once it hits the
      // target. Drop exercises whose solution fails its own tests on each attempt.
      let best: SeedCourse | null = null
      let bestKept = 0
      let bestDropped = 0
      for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
        const raw = await generator.generate({
          topic: topic.name,
          difficulty: 'beginner',
        })
        const course = generatedToSeedCourse(slug, 'beginner', raw)
        const { kept, dropped } = pruneExercises(course, JS_EXERCISE_SLUGS.has(slug))
        if (!best || course.lessons.length > best.lessons.length) {
          best = course
          bestKept = kept
          bestDropped = dropped
        }
        if (course.lessons.length >= COURSE_TARGET.minLessons) break
      }
      generated.set(slug, best!)
      const exNote =
        bestKept || bestDropped
          ? `, ${bestKept} exercise(s)${bestDropped ? ` (+${bestDropped} broken dropped)` : ''}`
          : ''
      console.log(`ok (${best!.lessons.length} lessons${exNote})`)
    } catch (err) {
      failed.push(slug)
      console.log(`FAILED — ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  // Merge: replace regenerated slugs, keep other existing generated courses,
  // and order by the topic catalog for stable diffs.
  const merged = new Map<string, SeedCourse>(
    GENERATED_BUILTIN_COURSES.map((c) => [c.topicSlug, c]),
  )
  for (const [slug, course] of generated) merged.set(slug, course)
  const ordered = SEED_TOPICS.map((t) => merged.get(t.slug)).filter(
    (c): c is SeedCourse => c !== undefined,
  )

  // Write atomically (temp + rename) so an interrupted run can never leave the
  // committed file truncated — which would brick the next run, since this script
  // imports GENERATED_BUILTIN_COURSES from it at startup.
  const tmpPath = `${OUT_PATH}.tmp`
  await writeFile(tmpPath, HEADER + JSON.stringify(ordered, null, 2) + '\n')
  await rename(tmpPath, OUT_PATH)
  console.log(`\nWrote ${ordered.length} course(s) to ${OUT_PATH}`)
  console.log('Review the content, then `npm run lint` + commit.')
  if (failed.length > 0) {
    console.error(`\n${failed.length} topic(s) failed: ${failed.join(', ')}`)
    process.exit(1)
  }
  process.exit(0)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
