import type { GitGoal } from '../core/git-sim'
import { AUTHORED_LESSONS } from './seed-content.authored'
import { GENERATED_BUILTIN_COURSES } from './seed-content.generated'

// Built-in starter course(s), seeded as shared courses (ownerUserId = null) so
// every user has real content to learn before generating their own. Pure +
// typed; ids are fixed so the seed runner (scripts/seed.ts) is idempotent.

export type SeedQuestion = {
  id: string
  type?: 'mcq' | 'short_answer' // defaults to mcq
  prompt: string
  options?: string[] // mcq only
  correctIndex?: number // mcq only
  expectedAnswer?: string // short_answer: the reference the AI grades against
  explanation: string
}

// A Phase 4 code exercise. `tests` match core/exercise.ts (evaluate `expression`
// against the learner's code and deep-compare to `expected`).
export type SeedJsExercise = {
  id: string
  kind?: 'js' // default; absent ⇒ 'js'
  prompt: string
  // Authoring language: 'ts' type-strips to JS, 'python' runs on Pyodide. Absent ⇒ 'js'.
  language?: 'js' | 'ts' | 'python'
  starterCode: string
  tests: { name: string; expression: string; expected: unknown }[]
  solution: string
  hint: string
}

// A terminal/git exercise (core/git-sim.ts): the learner types shell commands,
// success is `goals` asserted against the final repo state, `solution` is the
// command sequence that satisfies them, `setup` pre-runs before the learner.
export type SeedGitExercise = {
  id: string
  kind: 'git'
  prompt: string
  setup?: string[]
  goals: GitGoal[]
  solution: string[]
  hint: string
}

export type SeedExercise = SeedJsExercise | SeedGitExercise

export type SeedSegment = {
  id: string
  type:
    | 'reading'
    | 'code'
    | 'practice'
    | 'quiz'
    | 'hook'
    | 'mechanism'
    | 'predict'
    | 'reveal'
    | 'derive'
    | 'check'
  title: string
  markdown: string
  estMinutes: number
  questions: SeedQuestion[]
  exercise?: SeedExercise
}

export type SeedLesson = {
  id: string
  title: string
  estMinutes: number
  // Key terms the lesson introduces — linkified to further reading when the user
  // opts into "hyperlink key terms". Absent ⇒ no links (matches lessons.glossary).
  glossary?: string[]
  segments: SeedSegment[]
}

export type SeedCourse = {
  id: string
  topicSlug: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  lessons: SeedLesson[]
}

// Built-in courses, generated by `npm run gen:builtins` and committed after
// review, with any hand-authored lessons for that topic prepended.
//
// The merge happens here rather than in the generated file because
// gen:builtins rewrites that file wholesale — authored content has to live
// outside it or the next run destroys it. Prepending puts an authored lesson
// first, which is what a prerequisite is for: seed.ts takes orderIndex from
// array position.
export const BUILTIN_COURSES: SeedCourse[] = GENERATED_BUILTIN_COURSES.map(
  (course) => {
    const authored = AUTHORED_LESSONS[course.topicSlug]
    return authored ? { ...course, lessons: [...authored, ...course.lessons] } : course
  },
)
